Я еще доделаю, пока не всё работает(((
Gelnas/My_app pull request #5
Opened 2020-11-23 19:47 UTC by Gelnas

2020-11-24 11:53 UTC, Korgutlova requested changes

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/config/Config.java
> +//                User.builder()
удаляем неиспользуемый код

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/repository/PermissionRepository.java
> +public interface PermissionRepository extends JpaRepository<Permission, Long> {
`@Repository` аннотация

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/config/Config.java
> +    private UserServiceImpl usersService;
`final` модификатор

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/repository/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<Role, Long> {
`@Repository` аннотация

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<Users, Long> {
`@Repository` аннотация

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/PermissionServiceImpl.java
> +    private PermissionRepository permissionRepository;
`private final PermissionRepository permissionRepository;` добавляем модификатор

2020-11-24 11:53 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/UserService.java
> +
надеюсь тут будут методы) иначе зачем он нужен

2020-11-24 11:53 UTC, Korgutlova commented on src/main/resources/db/migration/V1_0_0_2__insert.sql
> +VALUES ('ROLE_USER'), ('ROLE_ADMIN'), ('ROLE_SUPERADMIN');
для `ROLE_SUPERADMIN` не увидела в конфиг файле настройку

2020-11-24 12:35 UTC, Gelnas commented
Здравствуйте. Вы не могли бы уделить мне немного времени онлайн. Я немного потерялась и за оставшееся время я не смогу всё исправить
--
Отправлено из Mail.ru для Android вторник, 24 ноября 2020г., 15:54 +04:00 от Korgutlova  notifications@github.com :

>@Korgutlova requested changes on this pull request.
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/config/Config.java :
> +                .authorizeRequests()
>+                .antMatchers(HttpMethod.GET, "/api/v1/**").hasAnyRole("ROLE_USER", "ROLE_ADMIN")
>+                .antMatchers(HttpMethod.GET, "/api/v1/**").hasAnyAuthority("READ", "WRITE")
>+                .antMatchers(HttpMethod.DELETE, "/api/v1/**").hasAnyRole("ADMIN")
>+                .antMatchers(HttpMethod.POST, "/api/v1/**").hasRole("ADMIN")
>+                .anyRequest()
>+                .authenticated()
>+                .and()
>+                .httpBasic();
>+    }
>+
>+//    @Bean
>+//    @Override
>+//    protected UserDetailsService userDetailsService() {
>+//        return new InMemoryUserDetailsManager(
>+//                User.builder()
>
>удаляем неиспользуемый код
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/repository/PermissionRepository.java :
> @@ -0,0 +1,7 @@
>+package com.simbirsoft.my_app.repository;
>+
>+import com.simbirsoft.my_app.model.Permission;
>+import org.springframework.data.jpa.repository.JpaRepository;
>+
>+public interface PermissionRepository extends JpaRepository {
>
>@Repository аннотация
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/config/Config.java :
> +import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
>+import org.springframework.security.config.annotation.web.builders.HttpSecurity;
>+import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
>+import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
>+import org.springframework.security.core.userdetails.User;
>+import org.springframework.security.core.userdetails.UserDetailsService;
>+import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
>+import org.springframework.security.crypto.password.PasswordEncoder;
>+import org.springframework.security.provisioning.InMemoryUserDetailsManager;
>+
>+@Configuration
>+@EnableWebSecurity
>+public class Config extends WebSecurityConfigurerAdapter {
>+
>+    @Autowired
>+    private UserServiceImpl usersService;
>
>final модификатор
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/repository/RoleRepository.java :
> @@ -0,0 +1,8 @@
>+package com.simbirsoft.my_app.repository;
>+
>+import com.simbirsoft.my_app.model.Role;
>+import org.springframework.data.jpa.repository.JpaRepository;
>+
>+public interface RoleRepository extends JpaRepository {
>
>@Repository аннотация
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/repository/UserRepository.java :
> @@ -0,0 +1,8 @@
>+package com.simbirsoft.my_app.repository;
>+
>+import com.simbirsoft.my_app.model.Users;
>+import org.springframework.data.jpa.repository.JpaRepository;
>+
>+public interface UserRepository extends JpaRepository {
>
>@Repository аннотация
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/service/Impl/PermissionServiceImpl.java :
> @@ -0,0 +1,20 @@
>+package com.simbirsoft.my_app.service.Impl;
>+
>+import com.simbirsoft.my_app.model.Permission;
>+import com.simbirsoft.my_app.model.Role;
>+import com.simbirsoft.my_app.repository.PermissionRepository;
>+import com.simbirsoft.my_app.repository.RoleRepository;
>+import com.simbirsoft.my_app.service.PermissionService;
>+import org.springframework.beans.factory.annotation.Autowired;
>+import org.springframework.stereotype.Service;
>+
>+@Service
>+public class PermissionServiceImpl implements PermissionService {
>+    @Autowired
>+    private PermissionRepository permissionRepository;
>
>private final PermissionRepository permissionRepository; добавляем модификатор
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/service/UserService.java :
> @@ -0,0 +1,5 @@
>+package com.simbirsoft.my_app.service;
>+
>+public interface UserService {
>+
>
>надеюсь тут будут методы) иначе зачем он нужен
>----------------------------------------------------------------------
>In  src/main/resources/db/migration/V1_0_0_2__insert.sql :
> @@ -0,0 +1,17 @@
>+INSERT INTO roles (role_)
>+VALUES ('ROLE_USER'), ('ROLE_ADMIN'), ('ROLE_SUPERADMIN');
>
>для ROLE_SUPERADMIN не увидела в конфиг файле настройку
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2020-11-24 13:38 UTC, Gelnas commented
Когда я ставлю final он выдает ошибку и требует инициализировать. 
 
 
--
С уважением, Гельназ Абдреева
 
  
>Вторник, 24 ноября 2020, 14:54 +03:00 от Korgutlova <notifications@github.com>:
> 
> 
>@Korgutlova requested changes on this pull request.
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/config/Config.java :
>> +                .authorizeRequests()
>
>+                .antMatchers(HttpMethod.GET, "/api/v1/**").hasAnyRole("ROLE_USER", "ROLE_ADMIN")
>
>+                .antMatchers(HttpMethod.GET, "/api/v1/**").hasAnyAuthority("READ", "WRITE")
>
>+                .antMatchers(HttpMethod.DELETE, "/api/v1/**").hasAnyRole("ADMIN")
>
>+                .antMatchers(HttpMethod.POST, "/api/v1/**").hasRole("ADMIN")
>
>+                .anyRequest()
>
>+                .authenticated()
>
>+                .and()
>
>+                .httpBasic();
>
>+    }
>
>+
>
>+//    @Bean
>
>+//    @Override
>
>+//    protected UserDetailsService userDetailsService() {
>
>+//        return new InMemoryUserDetailsManager(
>
>+//                User.builder()
>
>
>удаляем неиспользуемый код
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/repository/PermissionRepository.java :
>> @@ -0,0 +1,7 @@
>
>+package com.simbirsoft.my_app.repository;
>
>+
>
>+import com.simbirsoft.my_app.model.Permission;
>
>+import org.springframework.data.jpa.repository.JpaRepository;
>
>+
>
>+public interface PermissionRepository extends JpaRepository<Permission, Long> {
>
>
>@Repository аннотация
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/config/Config.java :
>> +import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
>
>+import org.springframework.security.config.annotation.web.builders.HttpSecurity;
>
>+import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
>
>+import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
>
>+import org.springframework.security.core.userdetails.User;
>
>+import org.springframework.security.core.userdetails.UserDetailsService;
>
>+import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
>
>+import org.springframework.security.crypto.password.PasswordEncoder;
>
>+import org.springframework.security.provisioning.InMemoryUserDetailsManager;
>
>+
>
>+@Configuration
>
>+@EnableWebSecurity
>
>+public class Config extends WebSecurityConfigurerAdapter {
>
>+
>
>+    @Autowired
>
>+    private UserServiceImpl usersService;
>
>
>final модификатор
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/repository/RoleRepository.java :
>> @@ -0,0 +1,8 @@
>
>+package com.simbirsoft.my_app.repository;
>
>+
>
>+import com.simbirsoft.my_app.model.Role;
>
>+import org.springframework.data.jpa.repository.JpaRepository;
>
>+
>
>+public interface RoleRepository extends JpaRepository<Role, Long> {
>
>
>@Repository аннотация
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/repository/UserRepository.java :
>> @@ -0,0 +1,8 @@
>
>+package com.simbirsoft.my_app.repository;
>
>+
>
>+import com.simbirsoft.my_app.model.Users;
>
>+import org.springframework.data.jpa.repository.JpaRepository;
>
>+
>
>+public interface UserRepository extends JpaRepository<Users, Long> {
>
>
>@Repository аннотация
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/service/Impl/PermissionServiceImpl.java :
>> @@ -0,0 +1,20 @@
>
>+package com.simbirsoft.my_app.service.Impl;
>
>+
>
>+import com.simbirsoft.my_app.model.Permission;
>
>+import com.simbirsoft.my_app.model.Role;
>
>+import com.simbirsoft.my_app.repository.PermissionRepository;
>
>+import com.simbirsoft.my_app.repository.RoleRepository;
>
>+import com.simbirsoft.my_app.service.PermissionService;
>
>+import org.springframework.beans.factory.annotation.Autowired;
>
>+import org.springframework.stereotype.Service;
>
>+
>
>+@Service
>
>+public class PermissionServiceImpl implements PermissionService {
>
>+    @Autowired
>
>+    private PermissionRepository permissionRepository;
>
>
>private final PermissionRepository permissionRepository; добавляем модификатор
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/service/UserService.java :
>> @@ -0,0 +1,5 @@
>
>+package com.simbirsoft.my_app.service;
>
>+
>
>+public interface UserService {
>
>+
>
>
>надеюсь тут будут методы) иначе зачем он нужен
>----------------------------------------------------------------------
>In  src/main/resources/db/migration/V1_0_0_2__insert.sql :
>> @@ -0,0 +1,17 @@
>
>+INSERT INTO roles (role_)
>
>+VALUES ('ROLE_USER'), ('ROLE_ADMIN'), ('ROLE_SUPERADMIN');
>
>
>для ROLE_SUPERADMIN не увидела в конфиг файле настройку
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 

2020-11-24 17:47 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/config/Config.java
> +    private UserServiceImpl usersService;
Когда я ставлю этот модификатор он требует инициализировать переменную. И Рамиль не ставил этот модификатор. В остальном посмотрите, пожалуйста, кажется всё работает)))

2020-11-25 18:13 UTC, nkorgutlova commented
> Здравствуйте. Вы не могли бы уделить мне немного времени онлайн. Я немного потерялась и за оставшееся время я не смогу всё исправить -- Отправлено из Mail.ru для Android вторник, 24 ноября 2020г., 15:54 +04:00 от Korgutlova notifications@github.com :
> […](#)
> @Korgutlova requested changes on this pull request. ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/config/Config.java : + .authorizeRequests() + .antMatchers(HttpMethod.GET, "/api/v1/**").hasAnyRole("ROLE_USER", "ROLE_ADMIN") + .antMatchers(HttpMethod.GET, "/api/v1/**").hasAnyAuthority("READ", "WRITE") + .antMatchers(HttpMethod.DELETE, "/api/v1/**").hasAnyRole("ADMIN") + .antMatchers(HttpMethod.POST, "/api/v1/**").hasRole("ADMIN") + .anyRequest() + .authenticated() + .and() + .httpBasic(); + } + +// @bean +// @override +// protected UserDetailsService userDetailsService() { +// return new InMemoryUserDetailsManager( +// User.builder() удаляем неиспользуемый код ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/repository/PermissionRepository.java : @@ -0,0 +1,7 @@ +package com.simbirsoft.my_app.repository; + +import com.simbirsoft.my_app.model.Permission; +import org.springframework.data.jpa.repository.JpaRepository; + +public interface PermissionRepository extends JpaRepository { @repository аннотация ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/config/Config.java : +import org.springframework.security.authentication.dao.DaoAuthenticationProvider; +import org.springframework.security.config.annotation.web.builders.HttpSecurity; +import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity; +import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter; +import org.springframework.security.core.userdetails.User; +import org.springframework.security.core.userdetails.UserDetailsService; +import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; +import org.springframework.security.crypto.password.PasswordEncoder; +import org.springframework.security.provisioning.InMemoryUserDetailsManager; + +@configuration +@EnableWebSecurity +public class Config extends WebSecurityConfigurerAdapter { + + @Autowired + private UserServiceImpl usersService; final модификатор ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/repository/RoleRepository.java : @@ -0,0 +1,8 @@ +package com.simbirsoft.my_app.repository; + +import com.simbirsoft.my_app.model.Role; +import org.springframework.data.jpa.repository.JpaRepository; + +public interface RoleRepository extends JpaRepository { @repository аннотация ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/repository/UserRepository.java : @@ -0,0 +1,8 @@ +package com.simbirsoft.my_app.repository; + +import com.simbirsoft.my_app.model.Users; +import org.springframework.data.jpa.repository.JpaRepository; + +public interface UserRepository extends JpaRepository { @repository аннотация ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/service/Impl/PermissionServiceImpl.java : @@ -0,0 +1,20 @@ +package com.simbirsoft.my_app.service.Impl; + +import com.simbirsoft.my_app.model.Permission; +import com.simbirsoft.my_app.model.Role; +import com.simbirsoft.my_app.repository.PermissionRepository; +import com.simbirsoft.my_app.repository.RoleRepository; +import com.simbirsoft.my_app.service.PermissionService; +import org.springframework.beans.factory.annotation.Autowired; +import org.springframework.stereotype.Service; + +@service +public class PermissionServiceImpl implements PermissionService { + @Autowired + private PermissionRepository permissionRepository; private final PermissionRepository permissionRepository; добавляем модификатор ---------------------------------------------------------------------- In src/main/java/com/simbirsoft/my_app/service/UserService.java : @@ -0,0 +1,5 @@ +package com.simbirsoft.my_app.service; + +public interface UserService { + надеюсь тут будут методы) иначе зачем он нужен ---------------------------------------------------------------------- In src/main/resources/db/migration/V1_0_0_2__insert.sql : @@ -0,0 +1,17 @@ +INSERT INTO roles (role_) +VALUES ('ROLE_USER'), ('ROLE_ADMIN'), ('ROLE_SUPERADMIN'); для ROLE_SUPERADMIN не увидела в конфиг файле настройку — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .

у меня было много задач по работе, не успевала посмотреть ваши домашки

2020-11-25 18:19 UTC, nkorgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/PermissionServiceImpl.java
> +    private PermissionRepository permissionRepository;
он требует инициализировать все верно, можно сделать аннотацию через lombok которая делает необходимый конструктор а можно руками прописать конструктор с параметром permissionRepository, и он автоматиечски туда заинджектит

2020-11-25 18:20 UTC, nkorgutlova commented on src/main/java/com/simbirsoft/my_app/config/Config.java
> +    private UserServiceImpl usersService;
@Gelnas хорошо, если Рамиль не ставил, то в данном классе не нужно

2020-11-25 19:58 UTC, Gelnas commented
Хорошо. Как раз в следующем ДЗ нужно так сделать)))
 
 
--
С уважением, Гельназ Абдреева
 
  
>Среда, 25 ноября 2020, 21:20 +03:00 от Natalya Korgutlova <notifications@github.com>:
> 
> 
>@nkorgutlova commented on this pull request.
>----------------------------------------------------------------------
>In  src/main/java/com/simbirsoft/my_app/service/Impl/PermissionServiceImpl.java :
>> @@ -0,0 +1,20 @@
>
>+package com.simbirsoft.my_app.service.Impl;
>
>+
>
>+import com.simbirsoft.my_app.model.Permission;
>
>+import com.simbirsoft.my_app.model.Role;
>
>+import com.simbirsoft.my_app.repository.PermissionRepository;
>
>+import com.simbirsoft.my_app.repository.RoleRepository;
>
>+import com.simbirsoft.my_app.service.PermissionService;
>
>+import org.springframework.beans.factory.annotation.Autowired;
>
>+import org.springframework.stereotype.Service;
>
>+
>
>+@Service
>
>+public class PermissionServiceImpl implements PermissionService {
>
>+    @Autowired
>
>+    private PermissionRepository permissionRepository;
>
>
>он требует инициализировать все верно, можно сделать аннотацию через lombok которая делает необходимый конструктор а можно руками прописать конструктор с параметром permissionRepository, и он автоматиечски туда заинджектит
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 

2020-11-25 22:26 UTC, Korgutlova reviewed
В целом код действительно рабочий, как ты и писала. Нужны некоторые доработки, когда попыталась запустить твою программу ругался на колонку у 
```
@Column(name = "date")
  private Calendar date;
``` 
(она должна называться `@Column(name = "dateN")` так как такое название в миграции). 

Также во многих местах заметила неверное форматирование, необходимо правильно делать отступы и тд.  

Про вытягивание пермишенов из ролей я написала, там немножко ты запуталась, но в целом это работет)

2020-11-25 22:26 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/UserServiceImpl.java
> +        Collection<Role> role = user.getRoles();
это поле в последующем не используется, стоит его убрать

2020-11-25 22:26 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/UserServiceImpl.java
> +    public  Role findByRole(String role_){return roleRepository.findByRole(role_);}
привести к формату названия переменных в Java role_ -> role

2020-11-25 22:26 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/UserServiceImpl.java
> +        String roleName = roles.stream().map(r -> new SimpleGrantedAuthority(r.getRole())).collect(Collectors.toList()).get(0).toString();
я правильно понимаю что мы вытаскиваем только одну роль из нескольких? по-хорошему наверное стоит взять все роли а по ним все пермишены. (но возомжно это не задача этой домашки)

второй вопрос вообще зачем тут преобразование в SimpleGrantedAuthority если по итогу мы просто вытаскиваем имя роли.

2020-11-25 22:26 UTC, Korgutlova commented on src/main/resources/db/migration/V1_0_0_2__insert.sql
> +VALUES (5.2, 2.6, 6), (9.5, 7.4, 6);
тут ты конечно поменяла миграционный файл, но по-хорошему так делать нельзя и нужно создавать нофую миграцию) 

  и да лучше удалить user_roles_permissions так как она не используется

2020-11-25 22:26 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/UserServiceImpl.java
> +        String roleName = roles.stream().map(r -> new SimpleGrantedAuthority(r.getRole())).collect(Collectors.toList()).get(0).toString();
например проще было сделать в таком стиле 
`return roles.stream().flatMap(role -> role.getPermissions().stream()).collect(Collectors.toList());`

по сути решение в одну строчку, так что можно было бы объединить с методом mapRolesToPermission 

и получить вообще такую итоговую функцию 

```
private Collection<? extends GrantedAuthority> mapRolesToPermission(Collection<Role> roles){
         return roles.stream()
                 .flatMap(role -> role.getPermissions().stream())
                 .map(permission -> new SimpleGrantedAuthority(permission.getPermission()))
                 .collect(Collectors.toList());
    }
```

2020-11-26 16:43 UTC, Gelnas commented on src/main/resources/db/migration/V1_0_0_2__insert.sql
> +VALUES (5.2, 2.6, 6), (9.5, 7.4, 6);
Хорошо. Но удалю эту таблицу в старой, хорошо?

2020-11-26 16:44 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/service/Impl/UserServiceImpl.java
> +        String roleName = roles.stream().map(r -> new SimpleGrantedAuthority(r.getRole())).collect(Collectors.toList()).get(0).toString();
Я думала просто в for их вытащить, но у меня пока 1 пользователь - 1 роль, поэтому решила так оставить

2020-11-26 16:48 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/service/Impl/UserServiceImpl.java
> +        String roleName = roles.stream().map(r -> new SimpleGrantedAuthority(r.getRole())).collect(Collectors.toList()).get(0).toString();
вот я над этим и ломала голову. Да Вы правы я запуталась. Спасибо))

2020-11-26 18:54 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/config/Config.java
> +    private UserServiceImpl usersService;
final нужно ставить если инжектим в поле через конструктор класса. То есть:

private final UserServiceImpl userService;

@Autowired
public Config(UserServiceImpl userService) {
  this.userService = userService;
}

либо используя Lombok:

@RequiredArgsConstructor
public class Config .... {
private final UserServiceImpl userService;

2020-11-26 18:55 UTC, Gelnas commented
Я буду это делать в новом дз)
--
Отправлено из Mail.ru для Android

2020-11-26 18:57 UTC, ramilmm commented
После исправлений комментов можешь мёржить

2020-11-26 19:05 UTC, merged