Homework4
Gelnas/My_app pull request #6
Opened 2020-11-30 18:06 UTC by Gelnas

У меня в каждом ___ServiсeImpl почему-то выделяет красным 
@Autowired
private ___Mapper ____Mapper; 
и не запускается как надо.

2020-11-30 23:18 UTC, Korgutlova reviewed
Я тебе отписала в чем ошибка, надеюсь разберешься. Так еще необходимо добавить сваггер он будет?)

2020-11-30 23:18 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/model/Rate.java
> +//@Builder
если не используем аннотации удалаяем закомментированный код

2020-11-30 23:18 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/ElectricityServiсeImpl.java
> +    private ElectricityMapper electricityMapper;
не работает потому что необходимо добавить аннотацию `@RequiredArgsConstructor` у класса

2020-11-30 23:18 UTC, Korgutlova commented on src/main/java/com/simbirsoft/my_app/service/Impl/ElectricityServiсeImpl.java
> +//                .date(electDto.getDate())
удаляем если не используем

2020-12-01 02:39 UTC, Gelnas commented
Спасибо. Да будет. Пока тоже немного не работает (
--
Отправлено из Mail.ru для Android

2020-12-01 14:16 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/service/Impl/ElectricityServiсeImpl.java
> +    private ElectricityMapper electricityMapper;
А данную аннотацию ко всем связанным классам добавлять? Или к мапперам и репозиториям?

2020-12-01 14:17 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/service/Impl/ElectricityServiсeImpl.java
> +    private ElectricityMapper electricityMapper;
Добавила к перечисленным не работает((

2020-12-01 14:21 UTC, Gelnas commented
По поводу сваггера описанное [здесь ](https://medium.com/@hala3k/setting-up-swagger-3-with-spring-boot-2-a7c1c3151545)у меня не срабатывает. Я находила туториалы, но там или другая версия или подключение не такое. В чем может быть проблема, не подскажете?

2020-12-01 18:33 UTC, ramilmm commented on pom.xml
> +		<dependency>
Это всё лишнее, от велосити до хмлЮнит включительно

2020-12-01 18:33 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/config/SpringFoxConfig.java
> +                .apis(RequestHandlerSelectors.any())
попробуй тут прописать явный путь до пакета с контроллерами
RequestHandlerSelectors.basePackage(*packageName*.controller)

2020-12-01 18:33 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/controller/RateController.java
> +    @ApiOperation(value = "find rate by id")
В контроллерах можно добавить описания возможных ответов (код, описание и схема по желанию)

2020-12-04 09:40 UTC, ramilmm requested changes
Посмотри мои комменты. Почисти неиспользуемые импорты. По остальному вопросов нет

2020-12-04 09:40 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/controller/RateController.java
> +            @ApiResponse(code = 404, message = "Not found", response = ResourceNotFoundException.class)
не совсем понятно зачем тут использовать ResourceNotFoundException из velocity?
Вообще велосити используется, как правило, для генерирования каких-то печатных форм, писем и т.д.
Может я не совсем понимаю, объясни пожалуйста)

2020-12-04 09:40 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/mapper/ExpenseMapper.java
> +            //@Mapping(target = "scoreWater", source = "waterId"),
неиспользуемый код лучше удалить

2020-12-04 09:40 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/model/Role.java
> +import lombok.RequiredArgsConstructor;
неиспользуемый импорт

2020-12-04 09:40 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/model/Users.java
> +import lombok.RequiredArgsConstructor;
и тут импорт лишний

2020-12-04 09:40 UTC, ramilmm commented on src/main/java/com/simbirsoft/my_app/repository/ElectricityRepository.java
> +
тут что-то съехало форматирование

2020-12-04 13:52 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/controller/RateController.java
> +            @ApiResponse(code = 404, message = "Not found", response = ResourceNotFoundException.class)
Ошибка)) 
Наткнулась на такое и не до конца разобравшись добавила. Думала хоть что-то выведет. Не правильно подумала...

2020-12-04 14:00 UTC, Gelnas commented on src/main/java/com/simbirsoft/my_app/mapper/ExpenseMapper.java
> +            //@Mapping(target = "scoreWater", source = "waterId"),
Я оставлю его, хорошо? Мне там до делать нужно)))

2020-12-04 14:10 UTC, Gelnas commented
Вроде всё учла, кроме одного момента. Можно делать merge?

2020-12-05 14:09 UTC, Korgutlova approved these changes
Да можешь мержить и доразберись с мапперами )

2020-12-05 14:14 UTC, Gelnas commented
Хорошо, спасибо)
--
Отправлено из Mail.ru для Android суббота, 05 декабря 2020г., 18:09 +04:00 от Korgutlova  notifications@github.com :

>@Korgutlova approved this pull request.
>Да можешь мержить и доразберись с мапперами )
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2020-12-05 14:27 UTC, merged